import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
    },
    header: {
        marginBottom: 20,
        borderBottom: 1,
        borderBottomColor: '#CCCCCC',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 12,
        color: '#666666',
    },
    section: {
        margin: 10,
        padding: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        backgroundColor: '#F0F0F0',
        padding: 5,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    label: {
        width: 100,
        fontSize: 12,
        fontWeight: 'bold',
    },
    value: {
        fontSize: 12,
    },
    resultBox: {
        marginTop: 10,
        padding: 10,
        border: 1,
        borderColor: '#000000',
        alignItems: 'center',
    },
    pass: {
        color: 'green',
        fontWeight: 'bold',
    },
    fail: {
        color: 'red',
        fontWeight: 'bold',
    },
});

interface ReportData {
    address: string;
    builder: string;
    date: string;
    ach50: number;
    volume: number;
    cfm50: number;
}

// Create Document Component
export const InspectionReportPDF = ({ data }: { data: ReportData }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Ulrich Energy Audit Report</Text>
                <Text style={styles.subtitle}>RESNET 380 / ANSI Standards</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Job Details</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Address:</Text>
                    <Text style={styles.value}>{data.address}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Builder:</Text>
                    <Text style={styles.value}>{data.builder}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Date:</Text>
                    <Text style={styles.value}>{data.date}</Text>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Blower Door Test Results</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Volume:</Text>
                    <Text style={styles.value}>{data.volume} ft³</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>CFM50:</Text>
                    <Text style={styles.value}>{data.cfm50}</Text>
                </View>

                <View style={styles.resultBox}>
                    <Text style={{ fontSize: 14, marginBottom: 5 }}>Calculated ACH50</Text>
                    <Text style={{ fontSize: 20, fontWeight: 'bold' }}>{data.ach50}</Text>
                    <Text style={data.ach50 <= 3.0 ? styles.pass : styles.fail}>
                        {data.ach50 <= 3.0 ? 'PASS' : 'FAIL'}
                    </Text>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={styles.subtitle}>Generated by Ulrich Energy Auditing Platform</Text>
            </View>
        </Page>
    </Document>
);
